(async function(){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>esc(v||'');
let d;
try{const r=await fetch('site.json',{cache:'no-store'});if(!r.ok)throw Error('site.json');d=await r.json()}catch(e){document.body.innerHTML='<main class="section"><div class="shell"><h1>Demo unavailable</h1></div></main>';return}
const q=new URLSearchParams(location.search),page=q.get('page')||'home',serviceSlug=q.get('service')||'';
const theme=d.brand||{};for(const [k,v] of Object.entries({accent:theme.accent,dark:theme.dark,soft:theme.soft})){if(v)document.documentElement.style.setProperty('--'+k,v)}
const href=(p,extra='')=>'index.html?page='+encodeURIComponent(p)+(extra?'&'+extra:'');
const brand=theme.logoUrl?'<span class="brand-logo-wrap"><img class="brand-logo" src="'+esc(theme.logoUrl)+'" alt="'+esc(d.name)+' logo"></span>':'<span class="brand">'+esc(d.name)+'</span>';
const nav='<header class="header"><div class="shell head"><a href="index.html">'+brand+'</a><nav class="nav">'+[['home','Home'],['about','About'],['services','Services'],['hours','Hours'],['gallery','Gallery'],['visit','Visit']].map(([k,l])=>'<a href="'+href(k)+'"'+(page===k?' class="active"':'')+'>'+l+'</a>').join('')+'</nav></div></header>';
const foot='<footer class="footer"><div class="shell"><strong>'+esc(d.name)+'</strong><span>'+esc(d.address||'')+'</span></div></footer>';
const concept='<div class="concept">Uncommissioned Chip In website concept</div>';
const img=(o,cls='feature-photo')=>o?.url?'<img class="'+cls+'" src="'+esc(o.url)+'" alt="'+esc(o.alt||'')+'">':'';
const cta=()=>'<div class="actions">'+(d.phone?'<a class="button" href="tel:'+esc(String(d.phone).replace(/[^+\d]/g,''))+'">Call '+esc(d.phone)+'</a>':'')+(d.email?'<a class="button alt" href="mailto:'+esc(d.email)+'">Email</a>':'')+'</div>';
function home(){
 const services=(d.services||[]).slice(0,6);
 return '<main><section class="hero"><div class="shell hero-grid"><div><p class="eyebrow">'+esc(d.hero?.eyebrow||'')+'</p><h1>'+esc(d.hero?.title||d.name)+'</h1><p class="lead">'+esc(d.hero?.strapline||'')+'</p><div class="actions"><a class="button" href="'+href('services')+'">Explore services</a><a class="button alt" href="'+href('visit')+'">Plan a visit</a></div></div><figure class="hero-photo">'+img(d.hero?.image,'')+'</figure></div></section><section class="section"><div class="shell intro"><div><p class="eyebrow">'+esc(d.about?.eyebrow||'About')+'</p><h2>'+esc(d.about?.heading||d.name)+'</h2><p class="lead">'+esc(d.about?.lead||'')+'</p><p>'+esc(d.about?.summary||'')+'</p></div>'+img(d.about?.image)+'</div></section><section class="section" style="background:#fff"><div class="shell"><p class="eyebrow">'+esc(d.servicesHeading||'Services')+'</p><h2>'+esc(d.servicesSubheading||'What we offer')+'</h2><div class="service-grid">'+services.map(s=>'<a class="service-card" href="'+href('service','service='+encodeURIComponent(s.slug))+'">'+(s.image?.url?'<img src="'+esc(s.image.url)+'" alt="'+esc(s.image.alt||s.name)+'">':'')+'<div class="service-copy"><h3>'+esc(s.name)+'</h3><p>'+esc(s.shortSummary||'')+'</p><span class="service-link">Find out more →</span></div></a>').join('')+'</div></div></section></main>';
}
function about(){return '<main><section class="page-hero"><div class="shell"><p class="eyebrow">'+esc(d.about?.eyebrow||'About')+'</p><h1>'+esc(d.about?.heading||d.name)+'</h1><p class="lead">'+esc(d.about?.lead||'')+'</p></div></section><section class="section"><div class="shell intro"><div>'+((d.about?.paragraphs||[]).map(p=>'<p>'+esc(p)+'</p>').join(''))+(d.about?.facts?.length?'<div class="quick-grid">'+d.about.facts.map(f=>'<div class="quick-card"><strong>'+esc(f.label||f)+'</strong><span>'+esc(f.value||'')+'</span></div>').join('')+'</div>':'')+'</div>'+img(d.about?.image)+'</div></section></main>'}
function services(){return '<main><section class="page-hero"><div class="shell"><p class="eyebrow">'+esc(d.servicesHeading||'Services')+'</p><h1>'+esc(d.servicesSubheading||'Explore our services')+'</h1></div></section><section class="section"><div class="shell service-grid">'+(d.services||[]).map(s=>'<a class="service-card" href="'+href('service','service='+encodeURIComponent(s.slug))+'">'+(s.image?.url?'<img src="'+esc(s.image.url)+'" alt="'+esc(s.image.alt||s.name)+'">':'')+'<div class="service-copy"><h3>'+esc(s.name)+'</h3><p>'+esc(s.shortSummary||'')+'</p><span class="service-link">View details →</span></div></a>').join('')+'</div></section></main>'}
function service(){
 const s=(d.services||[]).find(x=>x.slug===serviceSlug);if(!s)return services();
 const menu=(s.items||[]).length?'<div class="menu-list">'+s.items.map(x=>'<div class="menu-item"><div><h4>'+esc(x.name)+'</h4><p>'+esc(x.description||'')+'</p></div><div class="menu-item-price">'+money(x.price)+'</div></div>').join('')+'</div>':'';
 const facts=(s.facts||[]).length?'<div class="quick-grid">'+s.facts.map(f=>'<div class="quick-card"><strong>'+esc(f.label||'')+'</strong><span>'+esc(f.value||'')+'</span></div>').join('')+'</div>':'';
 return '<main><section class="page-hero"><div class="shell"><a class="back-link" href="'+href('services')+'">← All services</a><p class="eyebrow">'+esc(s.eyebrow||d.servicesHeading||'Services')+'</p><h1>'+esc(s.pageHeading||s.name)+'</h1><p class="lead">'+esc(s.lead||'')+'</p></div></section><section class="section"><div class="shell detail-grid">'+img(s.detailImage||s.image,'detail-hero-image')+'<div class="detail-copy"><h2>'+esc(s.heading||s.name)+'</h2>'+((s.detailParagraphs||[]).map(p=>'<p>'+esc(p)+'</p>').join(''))+menu+facts+'<div class="cta-panel"><h3>'+esc(s.ctaTitle||'Get in touch')+'</h3><p>'+esc(s.ctaText||'')+'</p>'+cta()+'</div>'+(s.contentMode==='illustrative'?'<p class="illustrative-note">Some service details are illustrative for this uncommissioned concept.</p>':'')+'</div></div></section></main>'
}
function hours(){return '<main><section class="page-hero"><div class="shell"><p class="eyebrow">Plan ahead</p><h1>Opening Hours</h1></div></section><section class="section"><div class="shell hours">'+(d.hours||[]).map(h=>'<div class="hours-row"><strong>'+esc(h.day)+'</strong><span>'+esc(h.display)+'</span></div>').join('')+'</div></section></main>'}
function gallery(){return '<main><section class="page-hero"><div class="shell"><p class="eyebrow">Gallery</p><h1>'+esc(d.galleryHeading||d.name)+'</h1></div></section><section class="section"><div class="shell gallery">'+(d.gallery||[]).map(g=>'<figure><img src="'+esc(g.url)+'" alt="'+esc(g.alt||'')+'"><figcaption>'+esc(g.caption||'')+'</figcaption></figure>').join('')+'</div></section></main>'}
function visit(){const map=d.address?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(d.address):'';return '<main><section class="page-hero"><div class="shell"><p class="eyebrow">Find us</p><h1>Visit '+esc(d.name)+'</h1></div></section><section class="section"><div class="shell visit"><div class="panel"><h2>Address</h2><address>'+esc(d.address||'')+'</address>'+(map?'<a class="button" href="'+esc(map)+'" target="_blank" rel="noopener">Open in Google Maps</a>':'')+'</div><div class="panel"><h2>Get in touch</h2>'+cta()+'<p><a href="'+href('hours')+'">See opening hours →</a></p></div></div></section></main>'}
const renders={home,about,services,service,hours,gallery,visit};document.body.innerHTML=concept+nav+(renders[page]||home)()+foot;
})();